version: '3.9'
services:

  contactservice:
    build: ./ContactService
    ports:
      - "5000:80"
    depends_on:
      - postgres
      - kafka  # Kafka servisine doğru bağımlılık

  reportservice:
    build: ./ReportService
    ports:
      - "5001:80"
    depends_on:
      - postgres
      - kafka  # Kafka servisine doğru bağımlılık

  postgres:
    image: postgres:14
    container_name: phonebook_postgres
    restart: always
    environment:
      POSTGRES_DB: PhonebookDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest  # Zookeeper imajını güncelledik
    container_name: phonebook_zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest  # Kafka imajını güncelledik
    container_name: phonebook_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper

volumes:
  pgdata:
