# Temel imajý seçiyoruz
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .

# Projeyi restore ediyoruz
RUN dotnet restore "ContactService.csproj"

# Projeyi build ediyoruz
RUN dotnet build "ContactService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ContactService.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

# Uygulamayý baþlatýyoruz
ENTRYPOINT ["dotnet", "ContactService.dll"]
